language: scala
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
scala:
  - 2.12.3
jdk:
# This is currently disabled because scalafmt does not run under java 1.7-.
#  - oraclejdk7
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION validate
